<a href="https://colab.research.google.com/github/Nishitha-31/MachineLearning/blob/main/ml_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
data = {
    "Weight": [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    "Height": [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    "Age": [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    "Gender": ["Male", "Male", "Male", "Male", "Male",
               "Female", "Female", "Female", "Female", "Female"]
}

df = pd.DataFrame(data)

df

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [ ]:
df["Gender"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

df

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [ ]:
X = df[["Height", "Age", "Gender"]]

y = df["Weight"]

print("Independent Variables (X):")
print(X)

print("\nDependent Variable (y):")
print(y)

Independent Variables (X):
   Height  Age  Gender
0    1.80   35       1
1    1.68   39       1
2    1.82   25       1
3    1.70   60       1
4    1.87   27       1
5    1.55   18       0
6    1.50   89       0
7    1.78   42       0
8    1.67   16       0
9    1.64   52       0

Dependent Variable (y):
0    79
1    69
2    73
3    95
4    82
5    55
6    69
7    71
8    64
9    69
Name: Weight, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

Training data: 8
Testing data: 2

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
y_pred = model.predict(X_test)

print("Predicted Weights:")
print(y_pred)

Predicted Weights:
[56.85651025 79.10576115]

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 76.57792714844265
R² Score: -11.252468343750825

In [ ]:
results = pd.DataFrame({
    "Actual Weight": y_test,
    "Predicted Weight": y_pred
})

results

   Actual Weight  Predicted Weight
8             64         56.856510
1             69         79.105761